application: blogofyiran
version: release
runtime: python27
api_version: 1
threadsafe: yes

derived_file_type:
- python_precompiled

# default_expiration: "365d"

handlers:
- url: /static
  static_dir: static

- url: /assets
  static_dir: assets
  
- url: /sample
  static_dir: sample

- url: /animated-logo
  static_dir: animated-logo

- url: /js
  static_dir: js

- url: /index.json
  static_files: index.json
  upload: index.json

- url: /.*
  static_files: index.html
  upload: index.html


skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*\.template)|
 (.*/RCS/.*)|
 (\..*)|
 )$
